language: python
python: 2.7
env:
- TOXENV=py27
- TOXENV=pypy
- TOXENV=py33
- TOXENV=py34
install:
- "./.travis-workarounds.sh"
- pip install tox
script: tox
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
    - irc.freenode.org#scrapy
deploy:
  provider: pypi
  distributions: bdist_wheel sdist
  user: scrapy
  password:
    secure: UnOnSBV254I8w44LXAwJgY3I1+Jnc+Oq7RlmYSfm6oq9qcWGrtXrPjFh6ZKV7RcrFDwFo4MtqI1E14X3DhPTmkTtDxsadbWESShE5a1SRYwQactRDW8QBQvwT8JEJy02GUAduoOznBQod7CegiccOygrAW1ULj+Fr72YVPN8tfI=
  on:
    tags: true
    all_branches: true
    repo: scrapy/queuelib
