language: python
python: 2.7
env:
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=py33

install:
    - ./.travis-workarounds.sh
    - pip install -M tox

script: tox

notifications:
    irc:
        channels:
            - "irc.freenode.org#scrapy"
        use_notice: true
        skip_join: true
