language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install nose
    - pip install --use-mirrors .
script:
    - nosetests queuelib
notifications:
    irc:
        channels:
            - "irc.freenode.org#scrapy"
        use_notice: true
        skip_join: true
